name: Electron Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Upgrade node-gyp
        run: npm install --global node-gyp@latest && (for /f "delims=" %P in ('npm prefix -g') do npm config set node_gyp"%P\node_modules\node-gyp\bin\node-gyp.js")
      - name: Install dependencies
        run: cd Dashboard && yarn --network-timeout 1000000000
      - name: Build
        run: cd Dashboard && yarn build
